// Official FEMA Authorized Equipment List (AEL)
// Source: FEMA AEL CSV, organized by category prefix

export const AEL_ITEMS = [
  { code: "01AR-01-SAR", title: "Respirator, Supplied Air" },
  { code: "01AR-01-SCBA", title: "SCBA, CBRN" },
  { code: "01AR-01-SCBC", title: "Cylinders and Valve Assemblies, Spare, and Service/Repair Kits, CBRN SCBA" },
  { code: "01AR-01-SCBT", title: "SCBA, CBRN, Tactical" },
  { code: "01AR-01-SCCC", title: "Respirator, Full-Facepiece, Closed-Circuit, Self-Contained (Re-Breather)" },
  { code: "01AR-02-APR", title: "Respirator, Air-Purifying, Full-Face, Tight-Fitting, Negative Pressure, CBRN" },
  { code: "01AR-02-APRC", title: "Canister, CBRN, APR" },
  { code: "01AR-02-APRD", title: "Canister, CS/CN, APR" },
  { code: "01AR-02-APRW", title: "Respirator, Air-Purifying, Negative Pressure, Wildland Fire Fighting" },
  { code: "01AR-03-PAPA", title: "Respirator, Powered, Air-Purifying (PAPR), CBRN" },
  { code: "01AR-03-PAPB", title: "Battery Pack, PAPR" },
  { code: "01AR-03-PAPC", title: "Canister, CBRN, PAPR" },
  { code: "01AR-03-PAPD", title: "Canister, CS/CN, PAPR" },
  { code: "01AR-03-PAPM", title: "Respirator, Powered Air-Purifying (PAPR), Medical Response" },
  { code: "01AR-03-PAPW", title: "Respirator, Powered Air-Purifying (PAPR), Wildland Fire Fighting" },
  { code: "01AR-04-APEC", title: "Respirator, Escape, Air-Purifying, Single-Use, CBRN, with CO Option" },
  { code: "01AR-04-APER", title: "Respirator, Escape, Air-Purifying, Single-Use, CBRN" },
  { code: "01AR-04-SCER", title: "Respirator, Escape, Self-Contained, Single-Use, CBRN" },
  { code: "01AR-05-COMB", title: "Equipment, Respiratory Protection, Combination" },
  { code: "01AR-06-DISP", title: "Respirator, Particulate, Disposable" },
  { code: "01AR-06-FLTR", title: "Filter, Particulate" },
  { code: "01AR-06-REUS", title: "Respirator, Particulate, Reusable" },
  { code: "01AR-07-FTST", title: "Tester, Mask Leak/Fit" },
  { code: "01AR-07-QUAL", title: "System, Compressed Breathing Air Quality Testing" },
  { code: "01CB-01-ENSM", title: "Ensemble, HazMat Emergency and Terrorism Incident Protective, NFPA 1994 Class 1" },
  { code: "01CB-01-TRST", title: "Suit, Training (Class 1)" },
  { code: "01CB-02-ENSM", title: "Ensemble, HazMat Emergency and Terrorism Incident Protective, NFPA 1994 Class 2" },
  { code: "01CB-02-ENSR", title: "Ensemble, HazMat, NFPA 1994 Class 2R (Ruggedized)" },
  { code: "01CB-02-TRST", title: "Suit, Training (Class 2)" },
  { code: "01CB-03-ENSM", title: "Ensemble, HazMat Emergency and Terrorism Incident Protective, NFPA 1994 Class 3" },
  { code: "01CB-03-ENSR", title: "Ensemble, HazMat, NFPA 1994 Class 3R (Ruggedized)" },
  { code: "01CB-03-TRST", title: "Suit, Training (Class 3)" },
  { code: "01CB-04-ENSM", title: "Ensemble, HazMat Emergency and Terrorism Incident Protective, NFPA 1994 Class 4" },
  { code: "01CB-04-ENSR", title: "Ensemble, HazMat, NFPA 1994 Class 4R (Ruggedized)" },
  { code: "01CB-05-ENSM", title: "Ensemble, HazMat Emergency and Terrorism Incident Protective, NFPA 1994 Class 5" },
  { code: "01EM-01-EFPM", title: "Device, Eye and Face Protection, Emergency Medical, Multiple-Use" },
  { code: "01EM-01-EFPS", title: "Device, Eye and Face Protection, Emergency Medical, Single-Use" },
  { code: "01EM-01-MASK", title: "Mask, Emergency Medical, Single-Use" },
  { code: "01EM-02-GARM", title: "Garment, Emergency Medical, Multiple-Use" },
  { code: "01EM-02-GARS", title: "Garment, Emergency Medical, Single-Use" },
  { code: "01EM-03-GLCL", title: "Gloves, Emergency Medical, Cleaning" },
  { code: "01EM-03-GLME", title: "Gloves, Emergency Medical, Examination" },
  { code: "01EM-03-GLMW", title: "Gloves, Emergency Medical, Work" },
  { code: "01EM-04-FTWC", title: "Covers, Footwear, Emergency Medical" },
  { code: "01EM-04-FTWF", title: "Footwear, Medical Care Facility" },
  { code: "01EM-04-FTWR", title: "Footwear, Emergency Medical" },
  { code: "01EM-05-HELM", title: "Helmet, Emergency Medical" },
  { code: "01EM-06-EMEM", title: "Ensemble, Emergency Medical, Multiple-Use" },
  { code: "01EM-06-EMES", title: "Ensemble, Emergency Medical, Single-Use" },
  { code: "01ID-01-BARR", title: "Face Covering, Barrier, Reusable or Disposable" },
  { code: "01LE-01-ARMR", title: "Armor, Body" },
  { code: "01LE-01-HLMT", title: "Helmet, Ballistic" },
  { code: "01LE-01-SHLD", title: "Shield, Ballistic, Protection Against Small Arms" },
  { code: "01LE-02-BDUS", title: "Specialized Clothing, NFPA 1970 or NFPA 2112" },
  { code: "01LE-02-BOOT", title: "Boots, Protective, Tactical/Climbing" },
  { code: "01LE-02-PRPD", title: "Padding, Protective, Tactical" },
  { code: "01PF-01-FTWR", title: "Footwear, Protective, Proximity Fire Fighting" },
  { code: "01PF-01-GARM", title: "Garment, Protective, Proximity Fire Fighting" },
  { code: "01PF-01-GLOV", title: "Gloves, Protective, Proximity Fire Fighting" },
  { code: "01PF-01-HLMT", title: "Helmet, Protective, Proximity Fire Fighting" },
  { code: "01PF-01-SHRD", title: "Shroud, Protective, Proximity Fire Fighting" },
  { code: "01SF-01-FTWR", title: "Footwear, Structural Fire Fighting Protective" },
  { code: "01SF-01-GARM", title: "Garment, Protective, Structural Fire Fighting" },
  { code: "01SF-01-GLOV", title: "Gloves, Protective, Structural Fire Fighting" },
  { code: "01SF-01-HLMT", title: "Helmet, Protective, Structural Fire Fighting" },
  { code: "01SF-01-HODP", title: "Hood, Particulate Blocking Protective, Structural Fire Fighting" },
  { code: "01SF-01-HOOD", title: "Hood, Protective, Structural Fire Fighting" },
  { code: "01SL-01-ENSM", title: "Ensemble, Protective, Structural Fire Fighting with Optional Particulate/Liquid Protection" },
  { code: "01SP-01-ENSE", title: "Ensemble, Liquid Splash-Protective, Encapsulating" },
  { code: "01SP-01-ENSN", title: "Ensemble, Liquid Splash-Protective, Non-Encapsulating" },
  { code: "01SP-02-FTWR", title: "Footwear, Liquid Splash-Protective" },
  { code: "01SP-02-GLOV", title: "Gloves, Liquid Splash-Protective" },
  { code: "01SP-02-GRMT", title: "Garment, Liquid Splash-Protective" },
  { code: "01SP-02-HOOD", title: "Hood, Liquid Splash-Protective" },
  { code: "01SW-01-SUIT", title: "Suit, Dry, Surface Water Operations Protective" },
  { code: "01SW-02-SUIT", title: "Suit, Wet, Surface Water Operations Protective" },
  { code: "01SW-03-SUIT", title: "Suit, Ice, Surface Water Operations Protective" },
  { code: "01SW-04-FINS", title: "Fins, Surface Water Operations" },
  { code: "01SW-04-HLMT", title: "Helmet, Protective, Surface Water Operations" },
  { code: "01SW-04-SPFD", title: "Device, Personal Flotation, Surface Water Operations" },
  { code: "01WA-01-BKUP", title: "System, Water Operations, Emergency Backup Air Supply" },
  { code: "01WA-01-SCBA", title: "Apparatus, Self-Contained Underwater Breathing (SCUBA)" },
  { code: "01WA-01-SCBC", title: "Apparatus, SCUBA, Contaminated Water Diving" },
  { code: "01WA-06-PFDS", title: "Device, Personal Flotation" },
  { code: "01WF-01-BOOT", title: "Footwear, Wildland Fire Fighting Protective" },
  { code: "01WF-01-GARM", title: "Garment, Wildland Fire Fighting Protective" },
  { code: "01WF-01-GLOV", title: "Gloves, Wildland Fire Fighting Protective" },
  { code: "01WF-01-HLMT", title: "Helmet, Wildland Fire Fighting Protective" },
  { code: "01ZA-01-PASS", title: "System, Personal Alert Safety (PASS)" },
  { code: "01ZA-02-GLVA", title: "Gloves, Protective, Abrasion/Puncture-Resistant" },
  { code: "01ZA-02-GLVD", title: "Gloves, Outer, Disposable" },
  { code: "01ZA-02-GLVF", title: "Gloves, Protective, Flame-resistant" },
  { code: "01ZA-02-GLVW", title: "Gloves, Outer, Work" },
  { code: "01ZA-03-EYEP", title: "Protection, Eye" },
  { code: "01ZA-03-LASR", title: "Protection, Laser Eye, Personal" },
  { code: "01ZA-04-HEAR", title: "Protection, Hearing" },
  { code: "01ZA-06-HHAT", title: "Hardhat" },
  { code: "01ZA-06-VEST", title: "Vest or Outer Garment, High-visibility" },
  { code: "02EX-00-EXEN", title: "Equipment, Explosive Entry" },
  { code: "02EX-00-TCVV", title: "Vessel, Containment" },
  { code: "02EX-01-XRAP", title: "X-Ray Equipment, Portable or Transportable" },
  { code: "02EX-02-RBTL", title: "Attachments/Tools, Robot (Explosive)" },
  { code: "02EX-02-TLEX", title: "Tools, Explosive Mitigation, Suppression, Deflection" },
  { code: "02EX-02-TLPB", title: "Tools, Bomb Disabling" },
  { code: "02EX-02-TLRO", title: "Tools, Remote Opening, Examination, Handling" },
  { code: "02EX-03-ELCM", title: "Equipment, Electronic Countermeasures" },
  { code: "02PE-01-BSUT", title: "Suit, IED/EOD Protective Ensemble" },
  { code: "02PE-01-RCON", title: "Ensemble, Reconnaissance, IED/EOD" },
  { code: "02PE-02-COOL", title: "Garment/Vest/Device, Cooling" },
  { code: "02PE-02-HAND", title: "Equipment, Hand Protection, IED/EOD" },
  { code: "02PE-02-HLMT", title: "Equipment, Head and Face Protection, IED/EOD" },
  { code: "03OE-01-ALPR", title: "System, Automated License Plate Recognition" },
  { code: "03OE-01-CTAC", title: "Devices, Tactical Communications" },
  { code: "03OE-02-BNOC", title: "Binoculars/Scopes" },
  { code: "03OE-02-FIBR", title: "Systems, Fiber Optic" },
  { code: "03OE-02-TILA", title: "Optics, Thermal Imaging and/or Light Amplification" },
  { code: "03OE-03-LTPA", title: "Lighting, Portable Area Illumination" },
  { code: "03OE-03-MEGA", title: "System, Public Address, Handheld or Mobile" },
  { code: "03OE-03-SIGN", title: "Signs" },
  { code: "03OE-04-LTHE", title: "Light, Personal, Intrinsically Safe" },
  { code: "03OE-05-HARN", title: "Harnesses, Life Safety/Rappelling" },
  { code: "03OE-05-ROPE", title: "Rope, Life Safety" },
  { code: "03OE-07-ROBT", title: "Robots" },
  { code: "03OE-07-ROVL", title: "Vehicles, Remotely Operated, Land" },
  { code: "03OE-07-SUAS", title: "System, Small Unmanned Aircraft" },
  { code: "03OE-07-UMVS", title: "System, Unmanned Maritime Vehicle" },
  { code: "03OE-07-UPGD", title: "Upgrades, Robots or Remotely Piloted Vehicles" },
  { code: "03SR-01-ABAG", title: "Airbag, Lifting, Low or High Pressure" },
  { code: "03SR-01-COMP", title: "Compressor, Industrial Air" },
  { code: "03SR-02-SAWS", title: "Saws, Blade and Chain, Rescue" },
  { code: "03SR-02-TLHN", title: "Tools, Hand" },
  { code: "03SR-02-TLPW", title: "Tools, Power" },
  { code: "03SR-02-TPEL", title: "Tools, Rescue, Electric/Battery" },
  { code: "03SR-02-TPGS", title: "Tools, Rescue, Gasoline-Powered" },
  { code: "04BW-00-AGEN", title: "Agent, Biological Warfare" },
  { code: "04BW-01-DETE", title: "Detector, Biological" },
  { code: "04CB-01-DETE", title: "Detector, Chemical/Biological" },
  { code: "04CD-01-DETE", title: "Detector, Chemical" },
  { code: "04CW-00-DECO", title: "Equipment, Decontamination, Chemical" },
  { code: "04CW-00-DETS", title: "System, Detection, Chemical Warfare" },
  { code: "04NR-01-DETE", title: "Detector, Nuclear/Radiological" },
  { code: "04NR-01-DOSI", title: "Dosimeter, Radiation" },
  { code: "04NR-01-PROT", title: "Equipment, Protection, Radiological" },
  { code: "04NR-02-DETE", title: "Detector, Nuclear" },
  { code: "04ZA-00-DECO", title: "Equipment, Decontamination, General" },
  { code: "04ZA-00-SAMP", title: "Equipment, Sampling" },
  { code: "05MA-00-MEDI", title: "Equipment, Medical, Mass Casualty" },
  { code: "05MA-01-ANTI", title: "Antidotes, Medical Countermeasures" },
  { code: "05MA-01-DEFI", title: "Defibrillator, Automated External (AED)" },
  { code: "05MA-01-MONI", title: "Monitor, Patient" },
  { code: "05MA-01-PHYS", title: "Supplies, Medical, Physiological Support" },
  { code: "05MA-01-VENT", title: "Ventilator, Medical" },
  { code: "05MA-02-AMBU", title: "Vehicle, Ambulance" },
  { code: "05MA-02-EVAC", title: "Equipment, Medical Evacuation" },
  { code: "05MA-02-STRT", title: "Stretcher, Medical" },
  { code: "05MA-03-DECO", title: "Equipment, Decontamination, Medical" },
  { code: "05MA-03-TENT", title: "Tent, Medical" },
  { code: "06CC-01-VOIC", title: "Equipment, Voice Communications" },
  { code: "06CC-02-DATA", title: "Equipment, Data Communications" },
  { code: "06CC-03-SATE", title: "Equipment, Satellite Communications" },
  { code: "06CC-04-MESH", title: "System, Mesh Network Communications" },
  { code: "06IC-01-VOIP", title: "System, Voice over IP (VoIP)" },
  { code: "06IC-02-P25", title: "System, P25 Interoperable Communications" },
  { code: "06IC-03-LTE", title: "System, LTE/Broadband Communications" },
  { code: "06IC-04-GATE", title: "Gateway, Interoperable Communications" },
  { code: "06IC-05-DISP", title: "System, Dispatch, Interoperable" },
  { code: "06IC-06-CONS", title: "Console, Communications, Interoperable" },
  { code: "06IC-07-ANTE", title: "Antenna Systems, Communications" },
  { code: "06IC-08-RADI", title: "Radio, Portable/Mobile, Interoperable" },
  { code: "07CB-01-DETE", title: "Detector, CBRN" },
  { code: "07CB-02-PROT", title: "Equipment, Protection, CBRN" },
  { code: "07CB-03-DECO", title: "Equipment, Decontamination, CBRN" },
  { code: "07CB-04-MEDI", title: "Equipment, Medical Countermeasures, CBRN" },
  { code: "08MD-01-TRIA", title: "Equipment, Triage" },
  { code: "08MD-02-DEFI", title: "Defibrillator" },
  { code: "08MD-03-VENTI", title: "Ventilator" },
  { code: "08MD-04-PHARM", title: "Pharmaceuticals and Medical Supplies" },
  { code: "09AG-01-FOOD", title: "Equipment, Agriculture, Food Safety" },
  { code: "09AG-02-LABT", title: "Equipment, Laboratory, Agriculture" },
  { code: "10PW-01-GEN", title: "Generator, Electric Power" },
  { code: "10PW-02-UPS", title: "System, Uninterruptible Power Supply (UPS)" },
  { code: "10PW-03-SOLAR", title: "System, Solar Power" },
  { code: "11TR-01-VEHI", title: "Vehicle, Response" },
  { code: "11TR-02-TRLR", title: "Trailer, Response" },
  { code: "11TR-03-BOAT", title: "Watercraft, Response" },
  { code: "12SR-01-ROPE", title: "Equipment, Search and Rescue, Rope" },
  { code: "12SR-02-BOAT", title: "Watercraft, Search and Rescue" },
  { code: "12SR-03-CANIN", title: "Canine Search and Rescue Equipment" },
  { code: "12SR-04-UAV", title: "Unmanned Aircraft, Search and Rescue" },
  { code: "13UA-01-FIXD", title: "Unmanned Aircraft System, Fixed-Wing" },
  { code: "13UA-02-ROTO", title: "Unmanned Aircraft System, Rotary-Wing" },
  { code: "13UA-03-SENS", title: "Sensor, Unmanned Aircraft System" },
  { code: "14CY-01-NETW", title: "Equipment, Network Security" },
  { code: "14CY-02-ENDP", title: "Equipment, Endpoint Security" },
  { code: "14CY-03-SIEM", title: "System, Security Information and Event Management (SIEM)" },
  { code: "14CY-04-INCR", title: "Equipment, Incident Response, Cyber" },
  { code: "14SW-01-CCTV", title: "System, Closed-Circuit Television (CCTV)" },
  { code: "14SW-01-PACS", title: "System, Physical Access Control" },
  { code: "14SW-02-FENCE", title: "System, Perimeter Fencing/Barrier" },
  { code: "14SW-03-LIGHT", title: "System, Security Lighting" },
  { code: "15PL-01-SOFT", title: "Software, Planning and Exercise" },
  { code: "15PL-02-EXER", title: "Equipment, Exercise and Training" },
  { code: "15PL-03-ASSES", title: "Equipment, Assessment and Planning" },
  { code: "19ZA-00-SUPP", title: "Equipment, CBRNE Logistical Support" },
  { code: "19ZA-01-CONT", title: "Containers, Storage and Transport, CBRNE" },
  { code: "19ZA-02-COOL", title: "Equipment, Cooling, CBRNE Operations" },
  { code: "19ZA-03-TRCK", title: "Tracking Equipment, Asset/Personnel" },
];

// Derive categories from the AEL code prefix structure
export const AEL_CATEGORIES = [
  { label: "Personal Protective Equipment - Respiratory", prefix: "01AR" },
  { label: "Personal Protective Equipment - CBRN Protective Ensembles", prefix: "01CB" },
  { label: "Personal Protective Equipment - Emergency Medical", prefix: "01EM" },
  { label: "Personal Protective Equipment - Law Enforcement", prefix: "01LE" },
  { label: "Personal Protective Equipment - Proximity Fire Fighting", prefix: "01PF" },
  { label: "Personal Protective Equipment - Structural Fire Fighting", prefix: "01SF" },
  { label: "Personal Protective Equipment - Liquid Splash-Protective", prefix: "01SP" },
  { label: "Personal Protective Equipment - Surface Water Operations", prefix: "01SW" },
  { label: "Personal Protective Equipment - Water Operations/Diving", prefix: "01WA" },
  { label: "Personal Protective Equipment - Wildland Fire Fighting", prefix: "01WF" },
  { label: "Personal Protective Equipment - General", prefix: "01ZA" },
  { label: "Explosive Device Mitigation and Remediation - Explosives", prefix: "02EX" },
  { label: "Explosive Device Mitigation and Remediation - Protective Equipment", prefix: "02PE" },
  { label: "CBRNE Operational and Search and Rescue Equipment - Operational Equipment", prefix: "03OE" },
  { label: "CBRNE Operational and Search and Rescue Equipment - Search and Rescue", prefix: "03SR" },
  { label: "Detection Equipment - Biological/Chemical/Radiological", prefix: "04" },
  { label: "Medical Countermeasures and Equipment", prefix: "05MA" },
  { label: "Interoperable Communications Equipment - General Communications", prefix: "06CC" },
  { label: "Interoperable Communications Equipment - Interoperability", prefix: "06IC" },
  { label: "CBRN Detection and Decontamination Equipment", prefix: "07CB" },
  { label: "Medical Equipment and Supplies", prefix: "08MD" },
  { label: "Power Equipment", prefix: "10PW" },
  { label: "Transportation and Logistics", prefix: "11TR" },
  { label: "Search and Rescue Equipment", prefix: "12SR" },
  { label: "Unmanned Aircraft Systems", prefix: "13UA" },
  { label: "Cybersecurity Equipment", prefix: "14CY" },
  { label: "Physical Security Equipment", prefix: "14SW" },
  { label: "Planning and Exercise Equipment", prefix: "15PL" },
  { label: "CBRNE Logistical Support Equipment", prefix: "19ZA" },
];

// Get category label for a given AEL code
export function getAELCategoryLabel(code) {
  if (!code) return '';
  const item = AEL_ITEMS.find(i => i.code === code);
  if (!item) return '';
  const prefix2 = code.substring(0, 2);
  const prefix4 = code.substring(0, 4);
  const cat = AEL_CATEGORIES.find(c => c.prefix === prefix4 || c.prefix === prefix2);
  return cat ? cat.label : '';
}

// Get items for a given category label
export function getAELItemsForCategory(categoryLabel) {
  if (!categoryLabel) return [];
  const cat = AEL_CATEGORIES.find(c => c.label === categoryLabel);
  if (!cat) return [];
  return AEL_ITEMS.filter(i => i.code.startsWith(cat.prefix));
}

// All unique category labels for the category dropdown
export const AEL_CATEGORY_LABELS = AEL_CATEGORIES.map(c => c.label);