// ─── Data Source Definitions ─────────────────────────────────────────────────
// Each source defines: label, entity fetcher key(s), field groups, default filters

export const DATA_SOURCES = {
  applications: {
    label: 'Applications',
    group: 'APPLICATIONS',
    entities: ['Application'],
    defaultFilters: [{ field: 'status', operator: 'is_not', value: 'Denied' }],
  },
  application_budgets: {
    label: 'Application Budget Lines',
    group: 'APPLICATIONS',
    entities: ['ApplicationBudget'],
    defaultFilters: [],
  },
  application_reviews: {
    label: 'Application Reviews',
    group: 'APPLICATIONS',
    entities: ['ApplicationReview'],
    defaultFilters: [],
  },
  funding_requests: {
    label: 'Funding Requests',
    group: 'FUNDING',
    entities: ['FundingRequest'],
    defaultFilters: [],
  },
  funding_request_lines: {
    label: 'Funding Request Line Items',
    group: 'FUNDING',
    entities: ['FundingRequestLineItem'],
    defaultFilters: [],
  },
  progress_reports: {
    label: 'Progress Reports',
    group: 'COMPLIANCE & REPORTING',
    entities: ['ProgressReport'],
    defaultFilters: [],
  },
  report_schedules: {
    label: 'Report Schedules',
    group: 'COMPLIANCE & REPORTING',
    entities: ['ReportSchedule'],
    defaultFilters: [{ field: 'status', operator: 'is_not', value: 'Approved' }],
  },
  compliance_flags: {
    label: 'Compliance Flags',
    group: 'COMPLIANCE & REPORTING',
    entities: ['ComplianceFlag'],
    defaultFilters: [{ field: 'is_resolved', operator: 'is_false', value: '' }],
  },
  organizations: {
    label: 'Organizations',
    group: 'ORGANIZATIONS',
    entities: ['Organization'],
    defaultFilters: [],
  },
  grant_programs: {
    label: 'Grant Programs',
    group: 'GRANTS & PROGRAMS',
    entities: ['GrantProgram'],
    defaultFilters: [],
  },
  nofos: {
    label: 'NOFOs',
    group: 'GRANTS & PROGRAMS',
    entities: ['Nofo'],
    defaultFilters: [],
  },
  // Combined
  apps_org_nofo: {
    label: 'Applications + Organization + NOFO',
    group: 'COMBINED VIEWS',
    entities: ['Application', 'Organization', 'Nofo'],
    join: { Application: { organization_id: 'Organization', nofo_id: 'Nofo' } },
    defaultFilters: [{ field: 'status', operator: 'is_not', value: 'Denied' }],
  },
  funding_app_org: {
    label: 'Funding Requests + Application + Organization',
    group: 'COMBINED VIEWS',
    entities: ['FundingRequest', 'Application', 'Organization'],
    join: { FundingRequest: { application_id: 'Application', organization_id: 'Organization' } },
    defaultFilters: [],
  },
  reports_app_org: {
    label: 'Progress Reports + Application + Organization',
    group: 'COMBINED VIEWS',
    entities: ['ProgressReport', 'Application', 'Organization'],
    join: { ProgressReport: { application_id: 'Application', organization_id: 'Organization' } },
    defaultFilters: [],
  },
  flags_app_org: {
    label: 'Compliance Flags + Application + Organization',
    group: 'COMBINED VIEWS',
    entities: ['ComplianceFlag', 'Application', 'Organization'],
    join: { ComplianceFlag: { application_id: 'Application', organization_id: 'Organization' } },
    defaultFilters: [{ field: 'is_resolved', operator: 'is_false', value: '' }],
  },
};

// Subrecipient-only sources
export const SUBRECIPIENT_SOURCES = {
  my_applications: { ...DATA_SOURCES.applications, label: 'My Applications' },
  my_funding_requests: { ...DATA_SOURCES.funding_requests, label: 'My Funding Requests' },
  my_progress_reports: { ...DATA_SOURCES.progress_reports, label: 'My Progress Reports' },
  my_report_schedules: { ...DATA_SOURCES.report_schedules, label: 'My Report Schedules' },
};

// ─── Field Definitions ────────────────────────────────────────────────────────

export const FIELD_GROUPS = {
  Application: [
    { key: 'application_number', label: 'Application Number', type: 'text' },
    { key: 'project_title', label: 'Project Title', type: 'text' },
    { key: 'organization_name', label: 'Organization Name', type: 'text' },
    { key: 'program_code', label: 'Program Code', type: 'dropdown', options: ['SHSP','UASI','EMPG','HSGP','NSGP','SLCGP','Other'] },
    { key: 'program_name', label: 'Program Name', type: 'text' },
    { key: 'nofo_title', label: 'NOFO Title', type: 'text' },
    { key: 'status', label: 'Status', type: 'dropdown', options: ['Draft','Submitted','PendingReview','UnderReview','RevisionRequested','Approved','Denied'] },
    { key: 'requested_amount', label: 'Requested Amount', type: 'currency' },
    { key: 'awarded_amount', label: 'Awarded Amount', type: 'currency' },
    { key: 'match_amount', label: 'Match Amount', type: 'currency' },
    { key: 'total_expended', label: 'Total Expended', type: 'currency' },
    { key: 'remaining_balance', label: 'Remaining Balance', type: 'currency' },
    { key: 'expenditure_rate', label: 'Expenditure Rate %', type: 'percent' },
    { key: 'performance_start', label: 'Performance Start', type: 'date' },
    { key: 'performance_end', label: 'Performance End', type: 'date' },
    { key: 'submitted_at', label: 'Submitted Date', type: 'date' },
    { key: 'created_date', label: 'Created Date', type: 'date' },
    { key: 'version', label: 'Version', type: 'number' },
    // Calculated
    { key: '_days_since_submission', label: 'ƒ Days Since Submission', type: 'calc',
      calc: row => row.submitted_at ? Math.floor((Date.now() - new Date(row.submitted_at)) / 86400000) : '' },
    { key: '_days_until_perf_end', label: 'ƒ Days Until Perf. End', type: 'calc',
      calc: row => row.performance_end ? Math.floor((new Date(row.performance_end) - Date.now()) / 86400000) : '' },
    { key: '_remaining_balance_calc', label: 'ƒ Remaining Balance', type: 'calc',
      calc: row => (row.awarded_amount || 0) - (row.total_expended || 0) },
  ],
  Organization: [
    { key: 'org_name', label: 'Organization Name', type: 'text', sourceKey: 'name' },
    { key: 'org_type', label: 'Organization Type', type: 'dropdown', sourceKey: 'type', options: ['County','Municipality','Nonprofit','Tribe'] },
    { key: 'org_county', label: 'County', type: 'text', sourceKey: 'county' },
    { key: 'org_city', label: 'City', type: 'text', sourceKey: 'city' },
    { key: 'org_state', label: 'State', type: 'text', sourceKey: 'state' },
    { key: 'org_ein', label: 'EIN', type: 'text', sourceKey: 'ein' },
  ],
  Nofo: [
    { key: 'nofo_title_field', label: 'NOFO Title', type: 'text', sourceKey: 'title' },
    { key: 'nofo_program_code', label: 'Program', type: 'dropdown', sourceKey: 'program_code', options: ['SHSP','UASI','EMPG','HSGP','NSGP','SLCGP','Other'] },
    { key: 'nofo_total_funding', label: 'Total Funding Available', type: 'currency', sourceKey: 'total_funding_available' },
    { key: 'nofo_open_date', label: 'NOFO Open Date', type: 'date', sourceKey: 'open_date' },
    { key: 'nofo_close_date', label: 'NOFO Close Date', type: 'date', sourceKey: 'close_date' },
  ],
  FundingRequest: [
    { key: 'request_number', label: 'Request Number', type: 'text' },
    { key: 'request_type', label: 'Request Type', type: 'dropdown', options: ['Reimbursement','Advance','Modification'] },
    { key: 'organization_name', label: 'Organization Name', type: 'text' },
    { key: 'application_number', label: 'Application Number', type: 'text' },
    { key: 'program_code', label: 'Program Code', type: 'text' },
    { key: 'period_start', label: 'Period Start', type: 'date' },
    { key: 'period_end', label: 'Period End', type: 'date' },
    { key: 'amount_requested', label: 'Amount Requested', type: 'currency' },
    { key: 'amount_approved', label: 'Amount Approved', type: 'currency' },
    { key: 'match_documented', label: 'Match Documented', type: 'currency' },
    { key: 'status', label: 'Status', type: 'dropdown', options: ['Submitted','UnderReview','AdditionalInfoRequested','Approved','Denied'] },
    { key: 'created_date', label: 'Created Date', type: 'date' },
  ],
  ComplianceFlag: [
    { key: 'organization_name', label: 'Organization Name', type: 'text' },
    { key: 'application_number', label: 'Application Number', type: 'text' },
    { key: 'flag_type', label: 'Flag Type', type: 'dropdown', options: ['OverdueReport','MissingDocument','FinancialDiscrepancy','MatchShortfall'] },
    { key: 'description', label: 'Description', type: 'text' },
    { key: 'severity', label: 'Severity', type: 'dropdown', options: ['Low','Medium','High','Critical'] },
    { key: 'is_resolved', label: 'Is Resolved', type: 'boolean' },
    { key: 'created_date', label: 'Created Date', type: 'date' },
    { key: '_age_days', label: 'ƒ Age (Days)', type: 'calc',
      calc: row => row.created_date ? Math.floor((Date.now() - new Date(row.created_date)) / 86400000) : '' },
  ],
  ReportSchedule: [
    { key: 'organization_name', label: 'Organization Name', type: 'text' },
    { key: 'application_number', label: 'Application Number', type: 'text' },
    { key: 'program_code', label: 'Program Code', type: 'text' },
    { key: 'report_type', label: 'Report Type', type: 'dropdown', options: ['Quarterly','Annual','Final'] },
    { key: 'period_start', label: 'Period Start', type: 'date' },
    { key: 'period_end', label: 'Period End', type: 'date' },
    { key: 'due_date', label: 'Due Date', type: 'date' },
    { key: 'status', label: 'Status', type: 'dropdown', options: ['Pending','Submitted','Overdue','Approved','Denied'] },
    { key: '_days_overdue', label: 'ƒ Days Overdue', type: 'calc',
      calc: row => row.status === 'Overdue' && row.due_date ? Math.floor((Date.now() - new Date(row.due_date)) / 86400000) : '' },
  ],
  ProgressReport: [
    { key: 'application_id', label: 'Application ID', type: 'text' },
    { key: 'submitted_by', label: 'Submitted By', type: 'text' },
    { key: 'expenditure_ytd', label: 'Expenditure YTD', type: 'currency' },
    { key: 'match_ytd', label: 'Match YTD', type: 'currency' },
    { key: 'status', label: 'Status', type: 'dropdown', options: ['Submitted','UnderReview','Approved','Denied','RevisionRequested'] },
    { key: 'submitted_at', label: 'Submitted Date', type: 'date' },
  ],
  Organization: [
    { key: 'name', label: 'Organization Name', type: 'text' },
    { key: 'type', label: 'Type', type: 'dropdown', options: ['County','Municipality','Nonprofit','Tribe'] },
    { key: 'county', label: 'County', type: 'text' },
    { key: 'city', label: 'City', type: 'text' },
    { key: 'state', label: 'State', type: 'text' },
    { key: 'ein', label: 'EIN', type: 'text' },
    { key: 'sam_uei', label: 'SAM UEI', type: 'text' },
    { key: 'is_active', label: 'Is Active', type: 'boolean' },
  ],
  GrantProgram: [
    { key: 'name', label: 'Program Name', type: 'text' },
    { key: 'code', label: 'Program Code', type: 'text' },
    { key: 'description', label: 'Description', type: 'text' },
    { key: 'federal_agency', label: 'Federal Agency', type: 'text' },
    { key: 'cfda_number', label: 'CFDA Number', type: 'text' },
    { key: 'is_active', label: 'Is Active', type: 'boolean' },
  ],
  Nofo: [
    { key: 'title', label: 'NOFO Title', type: 'text' },
    { key: 'program_code', label: 'Program Code', type: 'text' },
    { key: 'program_name', label: 'Program Name', type: 'text' },
    { key: 'total_funding_available', label: 'Total Funding Available', type: 'currency' },
    { key: 'min_award', label: 'Min Award', type: 'currency' },
    { key: 'max_award', label: 'Max Award', type: 'currency' },
    { key: 'open_date', label: 'Open Date', type: 'date' },
    { key: 'close_date', label: 'Close Date', type: 'date' },
    { key: 'status', label: 'Status', type: 'dropdown', options: ['Draft','UnderReview','Published','Closed','Archived'] },
  ],
  ApplicationReview: [
    { key: 'application_id', label: 'Application ID', type: 'text' },
    { key: 'reviewer_name', label: 'Reviewer Name', type: 'text' },
    { key: 'reviewer_email', label: 'Reviewer Email', type: 'text' },
    { key: 'action', label: 'Action', type: 'dropdown', options: ['Approved','Denied','RevisionRequested','NoteAdded'] },
    { key: 'score', label: 'Score', type: 'number' },
    { key: 'notes', label: 'Notes', type: 'text' },
    { key: 'created_date', label: 'Review Date', type: 'date' },
  ],
  ApplicationBudget: [
    { key: 'application_id', label: 'Application ID', type: 'text' },
    { key: 'budget_category', label: 'Category', type: 'dropdown', options: ['Personnel','Equipment','Training','Travel','Contractual','Planning','Other'] },
    { key: 'line_description', label: 'Description', type: 'text' },
    { key: 'amount_requested', label: 'Amount Requested', type: 'currency' },
    { key: 'amount_match', label: 'Match Amount', type: 'currency' },
    { key: 'is_allowable', label: 'Is Allowable', type: 'boolean' },
  ],
  FundingRequestLineItem: [
    { key: 'funding_request_id', label: 'Funding Request ID', type: 'text' },
    { key: 'budget_category', label: 'Category', type: 'dropdown', options: ['Personnel','Equipment','Training','Travel','Contractual','Planning','Other'] },
    { key: 'description', label: 'Description', type: 'text' },
    { key: 'amount', label: 'Amount', type: 'currency' },
    { key: 'is_allowable', label: 'Is Allowable', type: 'boolean' },
  ],
};

// Get all fields for a given data source key
export function getFieldsForSource(sourceKey) {
  const src = DATA_SOURCES[sourceKey] || SUBRECIPIENT_SOURCES[sourceKey];
  if (!src) return [];
  const groups = [];
  src.entities.forEach(entity => {
    const fields = FIELD_GROUPS[entity] || [];
    if (fields.length) groups.push({ group: entity + ' Fields', fields });
  });
  return groups;
}

export const REPORT_TEMPLATES = [
  {
    id: 'tpl_app_status',
    report_name: 'Application Status Summary',
    description: 'All applications grouped by status with counts and totals',
    icon: '📋',
    data_source: 'applications',
    selected_fields: [
      { key: 'application_number', label: 'App #' },
      { key: 'organization_name', label: 'Organization' },
      { key: 'program_code', label: 'Program' },
      { key: 'status', label: 'Status' },
      { key: 'requested_amount', label: 'Requested' },
      { key: 'awarded_amount', label: 'Awarded' },
      { key: 'submitted_at', label: 'Submitted' },
    ],
    filters: [{ field: 'status', operator: 'is_not', value: 'Draft' }],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'status', direction: 'asc' }],
  },
  {
    id: 'tpl_expenditure',
    report_name: 'Expenditure Rate by Grant',
    description: 'Awarded vs. expended by grant program and organization',
    icon: '💰',
    data_source: 'applications',
    selected_fields: [
      { key: 'application_number', label: 'App #' },
      { key: 'organization_name', label: 'Organization' },
      { key: 'program_code', label: 'Program' },
      { key: 'awarded_amount', label: 'Awarded' },
      { key: 'total_expended', label: 'Expended' },
      { key: 'remaining_balance', label: 'Remaining' },
      { key: 'expenditure_rate', label: 'Rate %' },
    ],
    filters: [{ field: 'status', operator: 'is', value: 'Approved' }],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'expenditure_rate', direction: 'desc' }],
  },
  {
    id: 'tpl_compliance',
    report_name: 'Compliance Flag Report',
    description: 'All open flags with severity, type, organization, and age in days',
    icon: '🚩',
    data_source: 'compliance_flags',
    selected_fields: [
      { key: 'organization_name', label: 'Organization' },
      { key: 'application_number', label: 'App #' },
      { key: 'flag_type', label: 'Flag Type' },
      { key: 'severity', label: 'Severity' },
      { key: 'description', label: 'Description' },
      { key: '_age_days', label: 'ƒ Age (Days)' },
      { key: 'created_date', label: 'Created' },
    ],
    filters: [{ field: 'is_resolved', operator: 'is_false', value: '' }],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'severity', direction: 'desc' }],
  },
  {
    id: 'tpl_funding_ledger',
    report_name: 'Funding Request Ledger',
    description: 'All funding requests with amounts, type, period, and approval status',
    icon: '📒',
    data_source: 'funding_requests',
    selected_fields: [
      { key: 'request_number', label: 'Request #' },
      { key: 'organization_name', label: 'Organization' },
      { key: 'application_number', label: 'App #' },
      { key: 'request_type', label: 'Type' },
      { key: 'period_start', label: 'Period Start' },
      { key: 'period_end', label: 'Period End' },
      { key: 'amount_requested', label: 'Requested' },
      { key: 'amount_approved', label: 'Approved' },
      { key: 'status', label: 'Status' },
    ],
    filters: [],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'created_date', direction: 'desc' }],
  },
  {
    id: 'tpl_report_tracker',
    report_name: 'Report Submission Tracker',
    description: 'All report schedules with due date, submission date, and status',
    icon: '📅',
    data_source: 'report_schedules',
    selected_fields: [
      { key: 'organization_name', label: 'Organization' },
      { key: 'application_number', label: 'App #' },
      { key: 'report_type', label: 'Type' },
      { key: 'due_date', label: 'Due Date' },
      { key: 'status', label: 'Status' },
      { key: '_days_overdue', label: 'ƒ Days Overdue' },
    ],
    filters: [],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'due_date', direction: 'asc' }],
  },
  {
    id: 'tpl_subrecipient_portfolio',
    report_name: 'Subrecipient Portfolio Summary',
    description: 'One row per organization showing grant count, total awarded, expended',
    icon: '🏛️',
    data_source: 'applications',
    selected_fields: [
      { key: 'organization_name', label: 'Organization' },
      { key: 'program_code', label: 'Program' },
      { key: 'application_number', label: 'App #' },
      { key: 'status', label: 'Status' },
      { key: 'awarded_amount', label: 'Awarded' },
      { key: 'total_expended', label: 'Expended' },
      { key: 'expenditure_rate', label: 'Rate %' },
    ],
    filters: [{ field: 'status', operator: 'is', value: 'Approved' }],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'organization_name', direction: 'asc' }],
  },
  {
    id: 'tpl_nofo_pipeline',
    report_name: 'NOFO Application Pipeline',
    description: 'Applications per NOFO with status breakdown and funding utilization',
    icon: '🔭',
    data_source: 'apps_org_nofo',
    selected_fields: [
      { key: 'application_number', label: 'App #' },
      { key: 'nofo_title', label: 'NOFO' },
      { key: 'organization_name', label: 'Organization' },
      { key: 'program_code', label: 'Program' },
      { key: 'status', label: 'Status' },
      { key: 'requested_amount', label: 'Requested' },
      { key: 'awarded_amount', label: 'Awarded' },
    ],
    filters: [],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'nofo_title', direction: 'asc' }],
  },
];

export const SUBRECIPIENT_TEMPLATES = [
  {
    id: 'tpl_my_grants',
    report_name: 'My Grant Status',
    description: 'All your applications with status and awarded amounts',
    icon: '📋',
    data_source: 'my_applications',
    selected_fields: [
      { key: 'application_number', label: 'App #' },
      { key: 'project_title', label: 'Project' },
      { key: 'program_code', label: 'Program' },
      { key: 'status', label: 'Status' },
      { key: 'requested_amount', label: 'Requested' },
      { key: 'awarded_amount', label: 'Awarded' },
    ],
    filters: [],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'submitted_at', direction: 'desc' }],
  },
  {
    id: 'tpl_my_expenditure',
    report_name: 'My Expenditure Summary',
    description: 'Funding requests per grant with expenditure rate',
    icon: '💰',
    data_source: 'my_funding_requests',
    selected_fields: [
      { key: 'request_number', label: 'Request #' },
      { key: 'application_number', label: 'App #' },
      { key: 'request_type', label: 'Type' },
      { key: 'amount_requested', label: 'Requested' },
      { key: 'amount_approved', label: 'Approved' },
      { key: 'status', label: 'Status' },
    ],
    filters: [],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'created_date', direction: 'desc' }],
  },
  {
    id: 'tpl_my_schedule',
    report_name: 'My Reporting Schedule',
    description: 'All report due dates with submission status',
    icon: '📅',
    data_source: 'my_report_schedules',
    selected_fields: [
      { key: 'application_number', label: 'App #' },
      { key: 'report_type', label: 'Type' },
      { key: 'due_date', label: 'Due Date' },
      { key: 'status', label: 'Status' },
      { key: '_days_overdue', label: 'ƒ Days Overdue' },
    ],
    filters: [],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [{ field: 'due_date', direction: 'asc' }],
  },
  {
    id: 'tpl_my_flags',
    report_name: 'My Compliance Flags',
    description: 'Your open compliance flags',
    icon: '🚩',
    data_source: 'my_applications',
    selected_fields: [
      { key: 'application_number', label: 'App #' },
      { key: 'status', label: 'Status' },
      { key: 'program_code', label: 'Program' },
    ],
    filters: [],
    filter_logic: 'AND',
    group_by: [],
    sort_rules: [],
  },
];